### ISSUE TITLE
PBS Playlist

### ISSUE THREAD

**Issue by adssa345** [dtankdempse/free-iptv-channels#1]
The Playlist link for just PBS is not working, can you fix it?

**Comment by dtankdempse** [comment]
The PBS playlist contains streams that use DRM. To ensure proper playback, the playlist is formatted using the **#KODIPROP** tag, which provides additional instructions to media players like Kodi.

### Common `#KODIPROP` Usage:
- **DRM or MPD Streams**:  
  `#KODIPROP:inputstream.adaptive.manifest_type=mpd`
- **License Keys (for Widevine DRM)**:  
  `#KODIPROP:inputstream.adaptive.license_key=...`

In short, `#KODIPROP` is a Kodi-specific tag that allows users to fine-tune how streams are handled by passing properties directly to Kodi’s input stream module (like `inputstream.adaptive` for adaptive streaming protocols such as MPEG-DASH and HLS).

Because these streams use DRM and MPEG-DASH (MPD), you'll need a player that supports these formats. I know that **TiviMate** can handle these streams, but I’m not sure which other players might be compatible.
