### ISSUE TITLE
Different tvg-ids in m3u and epg.

### ISSUE THREAD

**Issue by ls-milkyway** [dtankdempse/free-iptv-channels#3]
tvg-ids in the generated m3u file by google web app does not matches epg at [mjh](https://i.mjh.nz/)

For example:
SamsungTVPlus [m3u generated](https://cutt.ly/ZeTNyZnn) contains "tvg-id - (country code)" whereas epg (xml) at [mjh](https://i.mjh.nz/SamsungTVPlus/) contains only "tvg-id"

**Comment by dtankdempse** [comment]
Yeah, I didn't realize this was problem with the Samsung. I'll take a look at it. Thanks.

**Comment by dtankdempse** [comment]
Ok, I checked it. This was fixed a couple of weeks back. You just need to redeploy the [Google App Script](https://github.com/dtankdempse/free-iptv-channels/blob/main/code.gs).

**Comment by ls-milkyway** [comment]
> Ok, I checked it. This was fixed a week ago. You just need to redeploy the [Google App Script](https://github.com/dtankdempse/free-iptv-channels/blob/main/code.gs).
> 
> [Fixed an issue with Pluto](https://github.com/dtankdempse/free-iptv-channels/commit/bfd6c4c15ac83d2b4b43b6cc9c730f8681d8d0db). That fix would include Samsung also.

Just a noob question:

Every time you edit/commit code.js for improvements we need to re-deploy or just saving the new code in google app will be sufficient?

**Comment by dtankdempse** [comment]
Yes, that's correct. Every time changes are made in Google Apps Script, you need to redeploy it. It's much easier if you can just update a short link with the new deployment URL afterward.

As for issues, they aren't open on the plex-for-channels repository because I'm not the original developer. I only fixed the channel grouping. Any issues with the code should be directed to the original developer.
